# Assignment: CI / CD: Flask webapp with Docker & GitHub Actions
# Date: 09/21/2022
# "Hey Siri, play September by Earth, Wind & Fire"
# Author: derekYankie

# This workflow will publish a Flask webapp as an image to Docker Hub
# Using Github Actions
name: Push the Flask Webapp Docker image

# Track changes on main branch
on:
  push:
    branches: [ main ]
  
  # Uncomment this to track PR's
  # pull_request:
  #   branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag cheesburger/flask-github-actions-app
    
    - name: Build Message
      run: echo "Docker image built successfully!"
      
    - name: Push into Docker Hub
      run: docker push cheesburger/flask-github-actions-app:01
