name: Push the Flask Webapp Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag cheesburger/flask-github-actions-app
           echo "Docker image built successfully!"
      
    - name: Push into Docker Hub
      run: docker push cheesburger/flask-github-actions-app
           echo "Docker image pushed successfully!"
