name: outputs_demo
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output

    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      # Add a 3rd output
      output3: ${{ steps.step3.outputs.tagname }}
      
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
        # A bash variable that gets passed to the output
      - id: step3
        run: |
          tagvar=test12345
          echo "::set-output name=tagname::$tagvar"
  job2:
      runs-on: ubuntu-latest
      # Pass outputs from job1 (above)
      needs: job1
      steps:
        - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} ${{needs.job1.outputs.output3}}
