name: outputs_demo_2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.contents.data }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          # Exact version
          python-version: '3.9'
      - name: Run python script
        id: contents
        run: |
          python create_txt_file.py
          og_contents=$( cat readme.txt )
          contents=$( cat create_txt_file.py )
          echo "::set-output name=data::$contents"
  job2:
    runs-on: ubuntu-latest
    # Pass outputs from job1 (above)
    needs: job1
    steps:
      - run: echo "${{needs.job1.outputs.output1}}"
