# Assignment: Build a Python Build Deployment Pipeline
# Date: 01/30/2023
# "Hey Siri, play Element by Demeanor by Pop Smoke "
# Author: derekYankie

# This workflow will publish a Flask webapp as an image to Docker Hub
# Using Github Actions
name: Python Build Deployment

# Track changes and build a new image 
# when changes are committed to the repo
on:
  - push

# job-1 
jobs:
  build:
    name: Build ⚙️ # label for job-1
    runs-on: ubuntu-latest

    # steps for job-1
    # steps represent a sequence of tasks that will be executed as part of multi-jobs
    steps:
    - uses: actions/checkout@v3

    - name: Checkout 🛎️
      run: echo "Preparing build!"
    
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build Docker image 🐳
      run: docker build . --file Dockerfile --tag flask-github-actions-app:v1
    
    - name: List images
      run: docker images 
    
    - name: Tag Docker image
      run: docker tag flask-github-actions-app:v1 ${{ secrets.DOCKER_USERNAME }}/flask-github-actions-app:v2
    
    - name: Build Message
      run: echo "Docker image built successfully!"
      
    - name: Push into Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-github-actions-app:v2

  # job-2
  display:
    name: List images 📝 # label for job-2
    runs-on: ubuntu-latest
    needs: build # dependency 
    
    # steps for job-2
    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout 🛎️
      run: echo "Preparing list!"

    - name: List images 📝
      run: docker images

  # job-3
  tag:
    name: Tag images 📝 # label for job-2
    runs-on: ubuntu-latest
    needs: build # dependency 
    
    # steps for job-2
    steps:
    - uses: actions/checkout@v3
    
    - name: Checkout 🛎️
      run: echo "New Docker Image Tag!"

    - name: List images 📝
      run: docker images