name: Test and deploy Flask

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job called "test"
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
    -  uses: actions/checkout@v3
    
    # Set up Python 3.9 environment
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    # Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  # Run our unit tests using the test application
    - name: Run Tests
      run: |
        python test_app.py
deploy:
    # This job will run if "build" has ended successfully
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Set up Python 3.9 environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      # Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Check File List
        run: ls